language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_script:
    - cp phpunit.xml.dist phpunit.xml
    - cp config/autoload/local.php.dist config/autoload/local.php
    - cp config/autoload/database.php.dist config/autoload/database.local.php
    - COMPOSER_ROOT_VERSION=dev-master composer install

script:
    - php public/index.php load-sqlite --unlink
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
